/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tampilan;
import java.awt.Dimension; 
import java.awt.Toolkit; 
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.ResultSet; 
import java.sql.Statement; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author mrssy
 */
public class FormDataGejala extends javax.swing.JInternalFrame {
        String driver = "org.mariadb.jdbc.Driver"; 
        String db = "jdbc:mariadb://localhost:3306/bumil"; 
        String user = "root"; 
        String password = "";
        DefaultTableModel model;
    /**
     * Creates new form FormDataPenyakit
     */
    public FormDataGejala() {
        initComponents();
        TampilData();
        lebarkolom();
    }
    
    public void HapusTeks() { 
    txtKodeGejala.setText("");
    txtNamaGejala.setText(""); 
    

    }
    
    public void lebarkolom() {
        TableColumn column;
        tabelDataGejala.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column =  tabelDataGejala.getColumnModel().getColumn(0);
        column.setPreferredWidth(80);
        column =  tabelDataGejala.getColumnModel().getColumn(1);
        column.setPreferredWidth(680);
    }
    
    public void SimpanData(String kode, String namagejala) 
    { 
	try { 
	Class.forName(driver); 
	Connection con = DriverManager.getConnection(db, user, password); Statement stmt=con.createStatement(); 
	String queri="INSERT INTO gejala(kodeg, namag) VALUES"
                + "('"+kode+"','"+namagejala+"')"
                + "ON DUPLICATE KEY UPDATE namag='"+namagejala+"'"; 

	stmt.executeUpdate(queri); 
	javax.swing.JOptionPane.showMessageDialog(rootPane, "Data tersimpan"); 
	
	}catch(Exception ex) 
	{ 
	javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage()); 
	}
    } 
    
    void HapusData(String kode) 
    { 
	try { 
	Class.forName(driver); 
	Connection con = DriverManager.getConnection(db, user, password); 
	Statement stmt=con.createStatement();
	String queri="DELETE FROM gejala WHERE kodeg='"+kode+"'";
	stmt.executeUpdate(queri);
	javax.swing.JOptionPane.showMessageDialog(rootPane, "Data terhapus");
	
	}catch(Exception ex)
        {
	javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage()); 
      }	
    }  

    
    void TampilData() 
    { 
	try { 
	Class.forName(driver); 
	Connection con = DriverManager.getConnection(db, user, password); 
	Statement stmt=con.createStatement(); 
	String queri="SELECT * FROM gejala ORDER BY kodeg"; 
	ResultSet rs=stmt.executeQuery(queri);
	rs.last(); 
	
	int jumbaris=rs.getRow(); 
	String []titleKolom={"Kode Gejala","Nama Gejala"};
	String [][]datagejala=new String[jumbaris][2]; 
	int index=0; 
	
	model=new DefaultTableModel() { 
		public boolean isCellEditable(int rowIndex, int mColIndex) { 
		return false; 
		} 
		}; 
	
	rs=stmt.executeQuery(queri); 
	while(rs.next()) 
	{ 
            datagejala[index][0]=rs.getString("kodeg"); 
            datagejala[index][1]=rs.getString("namag"); 
            index++; 
	} 
	model.setDataVector(datagejala,titleKolom);
	tabelDataGejala.setModel(model);
        
        tabelDataGejala.getColumnModel().getColumn(0).setPreferredWidth(100); 	
        tabelDataGejala.getColumnModel().getColumn(1).setPreferredWidth(150);         
	rs.close(); 
	con.close(); 
    }catch(Exception ex) 
    { 
    javax.swing.JOptionPane.showMessageDialog(rootPane,ex.getMessage()); 
    } 
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelDataGejala = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtKodeGejala = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNamaGejala = new javax.swing.JTextArea();
        SIMPAN = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        HAPUS2 = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1250, 900));
        setMinimumSize(new java.awt.Dimension(1250, 900));
        setPreferredSize(new java.awt.Dimension(1250, 900));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA GEJALA PENYAKIT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(490, 490, 490))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        tabelDataGejala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Gejala", "Nama Gejala"
            }
        ));
        tabelDataGejala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataGejalaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelDataGejala);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Kode Gejala");

        txtKodeGejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeGejalaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nama Gejala");

        txtNamaGejala.setColumns(20);
        txtNamaGejala.setLineWrap(true);
        txtNamaGejala.setRows(5);
        jScrollPane3.setViewportView(txtNamaGejala);

        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        HAPUS2.setText("BERSIHKAN TEXT");
        HAPUS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUS2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeGejala, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(SIMPAN)
                        .addGap(18, 18, 18)
                        .addComponent(HAPUS)
                        .addGap(18, 18, 18)
                        .addComponent(HAPUS2)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodeGejala))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SIMPAN)
                            .addComponent(HAPUS)
                            .addComponent(HAPUS2))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        if(!txtKodeGejala.getText().isEmpty() && 
	!txtNamaGejala.getText().isEmpty()) 
	{ 
        String kode=txtKodeGejala.getText();
	String namagejala=txtNamaGejala.getText(); 

	SimpanData(kode,namagejala); 
	HapusTeks(); 
	TampilData(); 
	} else 
	     { 
            javax.swing.JOptionPane.showMessageDialog(rootPane,"Kode penyakit dan nama penyakit tidak boleh kosong,silahkan 		lengkapi data terlebih dahulu"); 
	}
    }//GEN-LAST:event_SIMPANActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
        String kode=tabelDataGejala.getModel().getValueAt
        ( tabelDataGejala.getSelectedRow(),0).toString();
        int respon=JOptionPane.showConfirmDialog(this, "Apakan anda yakin ingin menghapus data?", 			"Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(respon==0) //jika pengguna memilih iy, maka program akan menghapus data
        {
            HapusData(kode);
            TampilData();
            HapusTeks();
        }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void tabelDataGejalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataGejalaMouseClicked
        // TODO add your handling code here:
        txtKodeGejala.setText(tabelDataGejala.getModel().getValueAt
                        ( tabelDataGejala.getSelectedRow(),0).toString());
        txtNamaGejala.setText(tabelDataGejala.getModel().getValueAt
                        ( tabelDataGejala.getSelectedRow(),1).toString());  
    }//GEN-LAST:event_tabelDataGejalaMouseClicked

    private void txtKodeGejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeGejalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeGejalaActionPerformed

    private void HAPUS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUS2ActionPerformed
        // TODO add your handling code here:
        HapusTeks();
        
    }//GEN-LAST:event_HAPUS2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton HAPUS2;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabelDataGejala;
    private javax.swing.JTextField txtKodeGejala;
    private javax.swing.JTextArea txtNamaGejala;
    // End of variables declaration//GEN-END:variables
}
