/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tampilan;
import java.awt.Dimension; 
import java.awt.Toolkit; 
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.ResultSet; 
import java.sql.Statement; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mrssy
 */
public class FormDataPenyakit extends javax.swing.JInternalFrame {
        String driver = "org.mariadb.jdbc.Driver"; 
        String db = "jdbc:mariadb://localhost:3306/bumil"; 
        String user = "root"; 
        String password = "";
        DefaultTableModel model;
    /**
     * Creates new form FormDataPenyakit
     */
    public FormDataPenyakit() {
        initComponents();
        TampilData();
    }
    
    public void HapusTeks() { 
    txtKodePenyakit.setText(""); 
    txtNamaPenyakit.setText(""); 
    txtDeskripsi.setText(""); 
    txtSaran.setText(""); 
    

    }
    
    public void SimpanData(String kode, String namapenyakit, String deskripsi, String saran) 
    { 
	try { 
	Class.forName(driver); 
	Connection con = DriverManager.getConnection(db, user, password); Statement stmt=con.createStatement(); 
	String queri="INSERT INTO penyakit(kodep, namap, deskripp, saranp) VALUES"
                + "('"+kode+"','"+namapenyakit+"','"+deskripsi+"','"+saran+"')"
                + "ON DUPLICATE KEY UPDATE namap='"+ namapenyakit+"'"+",deskripp='"
                +deskripsi+ "',saranp='"+saran+"'"; 

	stmt.executeUpdate(queri); 
	javax.swing.JOptionPane.showMessageDialog(rootPane, "Data tersimpan"); 
	
	}catch(Exception ex) 
	{ 
	javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage()); 
	}
    } 
    
    void HapusData(String kode) 
    { 
	try { 
	Class.forName(driver); 
	Connection con = DriverManager.getConnection(db, user, password); 
	Statement stmt=con.createStatement();
	String queri="DELETE FROM penyakit WHERE kodep='"+kode+"'";
	stmt.executeUpdate(queri);
	javax.swing.JOptionPane.showMessageDialog(rootPane, "Data terhapus");
	
	}catch(Exception ex)
        {
	javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage()); 
      }	
    }  

    
    void TampilData() 
    { 
	try { 
	Class.forName(driver); 
	Connection con = DriverManager.getConnection(db, user, password); 
	Statement stmt=con.createStatement(); 
	String queri="SELECT * FROM penyakit ORDER BY kodep"; 
	ResultSet rs=stmt.executeQuery(queri);
	rs.last(); 
	
	int jumbaris=rs.getRow(); 
	String []titleKolom={"Kode Penyakit","Nama Penyakit","Deskripsi", "Saran"};
	String [][]datapenyakit=new String[jumbaris][4]; 
	int index=0; 
	
	model=new DefaultTableModel() { 
		public boolean isCellEditable(int rowIndex, int mColIndex) { 
		return false; 
		} 
		}; 
	
	rs=stmt.executeQuery(queri); 
	while(rs.next()) 
	{ 
            datapenyakit[index][0]=rs.getString("kodep"); 
            datapenyakit[index][1]=rs.getString("namap"); 
            datapenyakit[index][2]=rs.getString("deskripp"); 
            datapenyakit[index][3]=rs.getString("saranp");  
            index++; 
	} 
	model.setDataVector(datapenyakit,titleKolom);
	tabelDataPenyakit.setModel(model);
        
        tabelDataPenyakit.getColumnModel().getColumn(0).setPreferredWidth(100); 	
        tabelDataPenyakit.getColumnModel().getColumn(1).setPreferredWidth(150); 	
        tabelDataPenyakit.getColumnModel().getColumn(2).setPreferredWidth(170); 	
        tabelDataPenyakit.getColumnModel().getColumn(3).setPreferredWidth(170); 	 
	rs.close(); 
	con.close(); 
    }catch(Exception ex) 
    { 
    javax.swing.JOptionPane.showMessageDialog(rootPane,ex.getMessage()); 
    } 
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelDataPenyakit = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtKodePenyakit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSaran = new javax.swing.JTextArea();
        SIMPAN = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        HAPUS1 = new javax.swing.JButton();
        txtNamaPenyakit = new javax.swing.JTextField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1250, 900));
        setMinimumSize(new java.awt.Dimension(1250, 900));
        setPreferredSize(new java.awt.Dimension(1250, 900));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PENYAKIT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(504, 504, 504)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tabelDataPenyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Penyakit", "Nama Penyakit", "Deskripsi", "Saran"
            }
        ));
        tabelDataPenyakit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataPenyakitMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelDataPenyakit);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kode Penyakit");

        txtKodePenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodePenyakitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Penyakit");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Deskripsi Penyakit");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pencegahan Penyakit");

        txtSaran.setColumns(20);
        txtSaran.setLineWrap(true);
        txtSaran.setRows(5);
        jScrollPane3.setViewportView(txtSaran);

        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        HAPUS1.setText("BERSIHKAN TEXT");
        HAPUS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUS1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodePenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(SIMPAN)
                        .addGap(18, 18, 18)
                        .addComponent(HAPUS)
                        .addGap(18, 18, 18)
                        .addComponent(HAPUS1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodePenyakit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SIMPAN)
                            .addComponent(HAPUS)
                            .addComponent(HAPUS1))
                        .addGap(296, 296, 296))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodePenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodePenyakitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodePenyakitActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        if(!txtKodePenyakit.getText().isEmpty() && 
	!txtNamaPenyakit.getText().isEmpty()) 
	{ 
	String kodepenyakit=txtKodePenyakit.getText(); 
	String namapenyakit=txtNamaPenyakit.getText(); 
	String deskripsi=txtDeskripsi.getText(); 
	String saran=txtSaran.getText();

	SimpanData(kodepenyakit,namapenyakit,deskripsi,saran); 
	HapusTeks(); 
	TampilData(); 
	} else 
	     { 
            javax.swing.JOptionPane.showMessageDialog(rootPane,"Kode penyakit dan nama penyakit tidak boleh kosong,silahkan 		lengkapi data terlebih dahulu"); 
	}
    }//GEN-LAST:event_SIMPANActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
        String kode=tabelDataPenyakit.getModel().getValueAt
        ( tabelDataPenyakit.getSelectedRow(),0).toString();
        int respon=JOptionPane.showConfirmDialog(this, "Apakan anda yakin ingin menghapus data?", 			"Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(respon==0) //jika pengguna memilih iy, maka program akan menghapus data
        {
            HapusData(kode);
            TampilData();
            HapusTeks();
        }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void tabelDataPenyakitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataPenyakitMouseClicked
        // TODO add your handling code here:
        txtKodePenyakit.setText(tabelDataPenyakit.getModel().getValueAt
                        ( tabelDataPenyakit.getSelectedRow(),0).toString()); 
        txtNamaPenyakit.setText(tabelDataPenyakit.getModel().getValueAt
			( tabelDataPenyakit.getSelectedRow(),1).toString()); 
        txtDeskripsi.setText(tabelDataPenyakit.getModel().getValueAt
			( tabelDataPenyakit.getSelectedRow(),2).toString()); 
        txtSaran.setText(tabelDataPenyakit.getModel().getValueAt
			( tabelDataPenyakit.getSelectedRow(),3).toString()); 
    }//GEN-LAST:event_tabelDataPenyakitMouseClicked

    private void HAPUS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUS1ActionPerformed
        // TODO add your handling code here:
        HapusTeks();
        TampilData();
    }//GEN-LAST:event_HAPUS1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton HAPUS1;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabelDataPenyakit;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtKodePenyakit;
    private javax.swing.JTextField txtNamaPenyakit;
    private javax.swing.JTextArea txtSaran;
    // End of variables declaration//GEN-END:variables
}
